[workspace]
authors = ["gifdog97 <omusubset.s@gmail.com>"]
channels = ["conda-forge"]
name = "speech-babylm-dev"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
